# Generated by Django 4.2.2 on 2023-06-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='get_tasks',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
